run:
  algorithm:
    load_model: False
    model_path: "./models/weights/PPO_HumanPose/model_648000_steps.zip"
    type: "PPO"
  custom_policy:
    activation_function: "tanh"
    value_function:
      - 256
      - 256
      - 256
    policy_function:
      - 256
      - 256
      - 256
  train:
    num_envs : 24
    logging: 0
    timesteps: 15000000
    save_freq : 9000
    save_folder: "./models/weights"
    save_name: "HumanPose"
  eval:
    max_episodes: -1
    logging: 1
    display_delay: 0.00816666666
    show_world_aux: True
    show_goal_aux: True
    show_sensor_aux: True

env:
  max_steps_per_episode: 1024
  stat_buffer_size: 25
  normalize_observations: False
  normalize_rewards: False
  use_physics_sim: True
  gravity: [0, 0, -9.8]
  sim_step: 0.00416666666
  sim_steps_per_env_step: 1
  robots:
    - type: "UR5"
      report_joint_velocities: True
      config:
        name: "ur5_1"
        base_position: [0, 0, 0.01]
        base_orientation: [0, 0, -180]
        resting_angles: [-180, -45, -90, -135, 90, 0]
        control_mode: 2
        self_collision: True
        controlled_joints: ["shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint"]
      sensors:
        - type: "Obstacle"
          config:
            num_obstacles: 1
            max_distance: 0.2 # Distance in which obstacles are detected
            sphere_coordinates: False
            report_velocities: False
            reference_link_ids: [ "ee_link", "forearm_link", "wrist_1_link", "wrist_2_link", "wrist_3_link" ]
            #extra_points_link_pairs: [ [ "forearm_link", "wrist_1_link", 1 ], [ "forearm_link", "upper_arm_link", 1 ] ]
        # - type: "ObstacleAbsolute"
        #  config:
        #    num_obstacles: 1
        #    max_distance: 0.4
        #    report_velocities: False
        - type: "RobotSkeleton"
          config:
            report_velocities: False
            reference_link_ids: [ "ee_link", "forearm_link", "wrist_1_link", "wrist_2_link", "wrist_3_link" ]
            #extra_points_link_pairs: [ [ "forearm_link", "wrist_1_link", 1 ], [ "forearm_link", "upper_arm_link", 1 ] ]
      goal:
        type: "HumanPoseGoal"
        config:
          add_to_logging: True
          add_to_observation_space: True
  world:
    type: "HumanPoseWorld"
    config:
      workspace_boundaries: [ -100, 100, -100, 100, -100, 100 ]