# config that builds the env as Yifan had it
run:
  load_model: True  
  model_path: "./models/weights/PPO_Karim_test_arge/model_2880000_steps"
  train:
    num_envs : 16  
    timesteps: 15000000 
    save_freq : 15000
    save_folder: "./models/weights"  
    save_name: "PPO_Karim_test_arge"
    recurrent: False
    ppo_steps: 1024  
    batch_size: 512
    gamma: 0.99  
    tensorboard_folder: "./models/tensorboard_logs"
    custom_policy:
      use: True
      activation_function: "ReLU"  
      layers:
        - 256
        - 256
        - value_function:
          - 256
          - 256
        - policy_function:
          - 256
          - 256
          - 256  
      lstm:
        lstm_hidden_size: 512
        n_lstm_layers: 2
        shared_lstm: False
        enable_critic_lstm: True

  eval:
    max_episodes: -1  
    logging: 1
    display_delay: 0.00416666666
    show_world_aux: False
    show_goal_aux: True
    show_sensor_aux: False

env:
  max_steps_per_episode: 1024 
  stat_buffer_size: 25  
  normalize_observations: False
  normalize_rewards: False
  engine:
    type: "Pybullet"
    use_physics_sim: True
    gravity: [0, 0, -9.8]
    sim_step: 0.00416666666  #0.01666666666 
    sim_steps_per_env_step: 1 
  robots:
    - type: "UR5_Gripper" 
      config:
        name: "ur5_1"
        base_position: [0, 0, 0.01]
        base_orientation: [0, 0, -180]
        #resting_angles: [-180, -45, -90, -135, 90, 0]
        resting_angles: [-81.25, -90, -90, 0, 0, 0]
        control_mode: 2
        joint_vel_mul: 0.5
        #xyz_delta: 0.005
        #rpy_delta: 0.005
      goal:
        type: "PositionCollision"
        config:
          add_to_logging: True
          continue_after_success: True
          reward_success: 10
          reward_collision: -5
          reward_distance_mult: -0.01
          dist_threshold_start: 0.4
          dist_threshold_end : 0.01
          dist_threshold_increment_start: 0.01
          dist_threshold_increment_end: 0.001
          dist_threshold_overwrite: 0.06

  world:
    type: "Generated"
    config:
      workspace_boundaries: [-2, 2, -2, 2, -1, 5]
      start_override: 
      obstacles:
      - type: "box"
        position: [0.25, 0.25, -0.5]
        rotation: [0, 0, 0]
        params:
          halfExtents: [0.3, 0.3, 0.5]