run:
  algorithm:
    load_model: True  
    model_path: "./models/weights/PPO_platexperiment_end2end_1/model_interrupt"  
    type: "PPO"
    config:
      batch_size: 4048
      n_steps: 1024
      gamma: 0.9999
      ent_coef: 0.0002
    custom_policy:
      activation_function: "tanh"
      value_function:
        - 600
        - 500
        - 400
        - 300
        - 150
      policy_function:
        - 600
        - 300
        - 150
        - 75
        - 50
  train:
    num_envs : 24  
    logging: 0
    timesteps: 150000000 
    save_freq : 90000
    save_folder: "./models/weights"  
    save_name: "platexperiment_end2end_2"
  eval:
    max_episodes: -1
    logging: 1
    display_delay: 0
    show_world_aux: True
    show_goal_aux: True
    show_sensor_aux: False

env:
  max_steps_per_episode: 999999
  stat_buffer_size: 25  
  normalize_observations: False
  normalize_rewards: False
  use_physics_sim: True
  gravity: [0, 0, -9.8]
  sim_step: 0.00416666666 
  sim_steps_per_env_step: 1 
  robots:
    - type: "UR5_Gripper" 
      config:
        name: "ur5_1"
        base_position: [0, 0, 0.01]
        base_orientation: [0, 0, -180]
        resting_angles: [-180, -45, -90, -135, 90, 0]
        control_mode: 3
        self_collision: True
        controlled_joints: ["shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint"]
      sensors:
        - type: "Obstacle"
          config:
            update_steps: 1
            add_to_observation_space: True
            add_to_logging: False
            num_obstacles: 1
            max_distance: 0.2
            sphere_coordinates: False
            report_velocities: True
            reference_link_ids: ["ee_link", "forearm_link", "wrist_1_link", "wrist_3_link"]
        - type: "RobotSkeleton"
          config:
            update_steps: 1
            add_to_observation_space: True
            add_to_logging: False
            report_velocities: False
            reference_link_ids: ["ee_link", "forearm_link", "wrist_1_link", "wrist_3_link"]
            #extra_points_link_pairs: [["forearm_link", "wrist_1_link", 2]]
      goal:
        type: PositionCollisionTrajectory
        config:
          add_to_logging: True
          continue_after_success: True
          angle_threshold_start: 0.4
          angle_threshold_end : 0.05
          angle_threshold_increment_start: 0.01
          angle_threshold_increment_end: 0.001
          angle_threshold_overwrite: 0.4
  world:
    type: "Generated"
    config:
      workspace_boundaries: [-2, 2, -2, 2, 0, 2]
      obstacles:
      - type: "box"  # tisch
        position: [0.25, 0.25, -0.5]
        rotation: [0, 0, 0]
        params:
          halfExtents: [0.3, 0.3, 0.5]